paths:
  out_basedir: "src/tmp"
  user_history_path: "/data2/zhy/Movie_Recsys/Data/MovieLens_1M_data/user_history.json"

features:
  sparse_feature_names:
    - user_id
    - movie_id
    - user_gender
    - user_age
    - movie_year
    - user_occupation
    - user_history_favourite_genre

  dense_feature_names: []

  array_feature_names: []

  item_feature_names:
    - item_id

  user_feature_names:
    - user_id

  array_max_length: {}

embeddings:
  embedding_size:
    user_id: 32 # 16
    movie_id: 32 # 16
    user_gender: 8 # 8
    user_age: 8 # 8
    movie_year: 8 # 8
    user_occupation: 8 # 8
    movie_genres: 8 # 8

  embedding_table_size:
    user_id: 6040
    movie_id: 3883
    user_gender: 2
    user_age: 7
    movie_year: 18
    user_occupation: 21
    movie_genres: 19

  share_emb_table_features: # 共享embedding表的特征名称
    user_history_favourite_genre: movie_genres

dataset:
  batch_size: 256
  num_workers: 4
  pin_memory: true


train_hparams:
  val_freq: 9000
  lr: 1.0e-3
  min_lr: 5.0e-6
  lr_milestones:
    - 40000
    - 200000
  max_step: 300000
  device: "gpu"
  gpus:
    - 0